version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse/native:/run/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    environment:
      - OPENAI_API_KEY=your_openai_api_key
      - OPENAI_API_BASE=your_openai_api_base
      - OPENAI_API_DEPLOYMENT=your_openai_api_deployment
      - OPENAI_API_VERSION=your_openai_api_version
      - SDL_AUDIODRIVER=pulseaudio
      - AUDIODEV=hw:0,0
      - PULSE_SERVER=unix:/run/pulse/native
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/run/user/1000
    devices:
      - /dev/snd:/dev/snd
    user: root
    stdin_open: true
    tty: true
